# Generated by Django 4.2.5 on 2023-09-15 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataDesign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                (
                    "_width",
                    models.CharField(
                        choices=[
                            ("QUARTER", "QUARTER"),
                            ("THIRD", "THIRD"),
                            ("HALF", "HALF"),
                            ("TWO_THIRDS", "TWO_THIRDS"),
                            ("THREE_QUARTERS", "THREE_QUARTERS"),
                            ("FULL", "FULL"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "_comparison_type",
                    models.CharField(
                        choices=[
                            ("SINGLE", "SINGLE"),
                            ("BINARY", "BINARY"),
                            ("CONTINUOUS", "CONTINUOUS"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "_paradigm",
                    models.CharField(
                        choices=[("CR", "CR"), ("D3", "D3")], max_length=2
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="DataPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("lesp_code", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="Row",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=256, null=True)),
                ("documentation", models.TextField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("grouped", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ColumnChart",
            fields=[
                (
                    "datadesign_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="smartcharts.datadesign",
                    ),
                ),
                ("columns", models.ManyToManyField(to="smartcharts.datapoint")),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("smartcharts.datadesign",),
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1024)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smartcharts.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="RowItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smartcharts.datadesign",
                    ),
                ),
                (
                    "row",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smartcharts.row",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="row",
            name="items",
            field=models.ManyToManyField(
                through="smartcharts.RowItem", to="smartcharts.datadesign"
            ),
        ),
        migrations.AddField(
            model_name="row",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="smartcharts.section"
            ),
        ),
        migrations.CreateModel(
            name="Factoid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_string", models.TextField(blank=True, null=True)),
                ("data_points", models.ManyToManyField(to="smartcharts.datapoint")),
            ],
        ),
        migrations.CreateModel(
            name="StatList",
            fields=[
                (
                    "datadesign_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="smartcharts.datadesign",
                    ),
                ),
                (
                    "stat",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="smartcharts.datapoint",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("smartcharts.datadesign",),
        ),
        migrations.CreateModel(
            name="GroupedColumnChart",
            fields=[
                (
                    "datadesign_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="smartcharts.datadesign",
                    ),
                ),
                ("sub_charts", models.ManyToManyField(to="smartcharts.columnchart")),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("smartcharts.datadesign",),
        ),
    ]
