# Generated by Django 4.2.5 on 2023-09-16 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smartcharts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datadesign",
            name="compare_geographies",
            field=models.BooleanField(default=True),
        ),
    ]
