# Generated by Django 4.2.5 on 2023-09-19 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("smartcharts", "0002_datadesign_compare_geographies"),
    ]

    operations = [
        migrations.AddField(
            model_name="statlist",
            name="geo_compare",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="row",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rows",
                to="smartcharts.section",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="smartcharts.profile",
            ),
        ),
        migrations.CreateModel(
            name="DoughnutChart",
            fields=[
                (
                    "datadesign_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="smartcharts.datadesign",
                    ),
                ),
                ("slices", models.ManyToManyField(to="smartcharts.datapoint")),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("smartcharts.datadesign",),
        ),
        migrations.CreateModel(
            name="ColumnChartManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
    ]
