# Generated by Django 4.2.5 on 2023-09-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smartcharts", "0003_statlist_geo_compare_alter_row_section_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statlist",
            name="geo_compare",
        ),
        migrations.AddField(
            model_name="statlist",
            name="stat_type",
            field=models.CharField(
                choices=[
                    ("VAL", "Numeric value"),
                    ("PCT", "Percentage"),
                    ("RTO", "Ratio"),
                ],
                default="VAL",
                max_length=3,
            ),
            preserve_default=False,
        ),
    ]
