# Generated by Django 4.2.5 on 2023-09-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smartcharts", "0005_datapoint_display_name_alter_statlist_stat_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="datapoint",
            old_name="title",
            new_name="identifier",
        ),
        migrations.AddField(
            model_name="datadesign",
            name="identifier",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="datadesign",
            name="title",
            field=models.CharField(max_length=256),
        ),
    ]
